# Generated by Django 5.1.2 on 2024-11-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_petpost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petpost',
            name='location',
        ),
    ]
