# Generated by Django 5.1.2 on 2024-11-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0005_remove_petpost_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpost',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='petpost',
            name='division',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
